package com.wordtomarkdown;

import com.vladsch.flexmark.html2md.converter.FlexmarkHtmlConverter;
import org.zwobble.mammoth.DocumentConverter;
import org.zwobble.mammoth.Result;

import java.io.File;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Conversión de documentos Word a Markdown. No depende de la interfaz gráfica,
 * de modo que puede usarse y probarse por separado.
 *
 * <p>El flujo es {@code .docx → [Mammoth] → HTML → [flexmark] → .md}, ya que la
 * librería Java de Mammoth no ofrece conversión directa a Markdown.
 */
public class ConversionService {

    private static final String DOCX_EXTENSION = ".docx";

    /** Sufijo de la carpeta donde se extraen las imágenes de un documento. */
    private static final String IMAGE_DIR_SUFFIX = "_images";

    /** Fragmentos de alt text con los que Word marca las descripciones generadas por IA. */
    private static final List<String> AI_ALT_TEXT_MARKERS = List.of(
        "ia puede ser",
        "generated by ai",
        "generado por ia"
    );

    /** true si el archivo es un documento Word convertible. */
    public boolean isDocx(File file) {
        return file != null
            && file.isFile()
            && hasDocxExtension(file.getName())
            && !isWordTempFile(file.getName());
    }

    /**
     * Documentos .docx directamente contenidos en la carpeta, ordenados por nombre.
     * No se recorren las subcarpetas.
     *
     * <p>Se ignoran los archivos temporales que Word deja al abrir un documento
     * ("~$nombre.docx"), que no son documentos válidos.
     */
    public List<File> findDocxFiles(File folder) {
        if (folder == null || !folder.isDirectory()) {
            return List.of();
        }
        File[] files = folder.listFiles(f -> f.isFile()
            && hasDocxExtension(f.getName())
            && !isWordTempFile(f.getName()));
        if (files == null) {
            return List.of();
        }
        return Arrays.stream(files)
            .sorted(Comparator.comparing(File::getName, String.CASE_INSENSITIVE_ORDER))
            .toList();
    }

    /** Nombre del documento sin la extensión .docx. */
    public String baseNameOf(File docx) {
        String name = docx.getName();
        return hasDocxExtension(name) ? name.substring(0, name.length() - DOCX_EXTENSION.length()) : name;
    }

    /**
     * Convierte un documento y escribe el .md junto al original. Nunca lanza:
     * los fallos se describen en el {@link ConversionResult} devuelto.
     */
    public ConversionResult convert(File docx) {
        String baseName = baseNameOf(docx);
        File parent = docx.getAbsoluteFile().getParentFile();
        File output = new File(parent, baseName + ".md");
        Path imageDir = parent.toPath().resolve(baseName + IMAGE_DIR_SUFFIX);

        // Numera las imágenes encontradas (para nombres únicos) y contabiliza
        // por separado las extraídas con éxito y las que fallaron.
        AtomicInteger imageCounter = new AtomicInteger(0);
        AtomicInteger imagesOk = new AtomicInteger(0);
        List<String> imageErrors = Collections.synchronizedList(new ArrayList<>());

        try {
            DocumentConverter converter = new DocumentConverter()
                .imageConverter(image -> {
                    Map<String, String> attrs = new HashMap<>();
                    int index = imageCounter.incrementAndGet();
                    String imgName = null;
                    try {
                        Files.createDirectories(imageDir);
                        imgName = "image" + index + "." + extensionFor(image.getContentType());
                        try (InputStream is = image.getInputStream()) {
                            Files.copy(is, imageDir.resolve(imgName));
                        }
                        attrs.put("src", baseName + IMAGE_DIR_SUFFIX + "/" + imgName);
                        attrs.put("alt", cleanAltText(image.getAltText().orElse(null), index));
                        imagesOk.incrementAndGet();
                    } catch (Exception ex) {
                        // Una imagen ilegible no debe abortar el documento, pero tampoco
                        // puede pasar inadvertida: queda anotada y señalada en el Markdown.
                        imageErrors.add(describeImageError(index, imgName, ex));
                        attrs.put("src", "");
                        attrs.put("alt", "imagen " + index + " (no se pudo extraer)");
                    }
                    return attrs;
                });

            Result<String> htmlResult = converter.convertToHtml(docx);
            Set<String> warnings = htmlResult.getWarnings();

            String markdown = FlexmarkHtmlConverter.builder().build().convert(htmlResult.getValue());
            Files.writeString(output.toPath(), markdown, StandardCharsets.UTF_8);

            return new ConversionResult(
                docx, output, true, null,
                List.copyOf(warnings),
                imagesOk.get(),
                List.copyOf(imageErrors),
                imageDir
            );

        } catch (Exception ex) {
            return ConversionResult.failure(docx, output, imageDir, messageOf(ex));
        }
    }

    private boolean hasDocxExtension(String name) {
        return name.toLowerCase().endsWith(DOCX_EXTENSION);
    }

    /** Archivos "~$nombre.docx" (temporales de Word) y ocultos. */
    private boolean isWordTempFile(String name) {
        return name.startsWith("~$") || name.startsWith(".");
    }

    /** Extensión a partir del tipo MIME, normalizando compuestos como "svg+xml". */
    private String extensionFor(String contentType) {
        if (contentType == null || !contentType.contains("/")) {
            return "png";
        }
        String ext = contentType.split("/")[1];
        return ext.contains("+") ? ext.split("\\+")[0] : ext;
    }

    /**
     * Alt text utilizable: descarta el vacío y los avisos que añade automáticamente
     * la IA de Word, sustituyéndolos por un texto genérico.
     */
    private String cleanAltText(String altText, int index) {
        if (altText != null) {
            String trimmed = altText.trim();
            String lower = trimmed.toLowerCase();
            boolean generatedByAi = AI_ALT_TEXT_MARKERS.stream().anyMatch(lower::contains);
            if (!trimmed.isBlank() && !generatedByAi) {
                return trimmed;
            }
        }
        return "imagen " + index;
    }

    private String describeImageError(int index, String imgName, Exception ex) {
        return "imagen " + index
            + (imgName != null ? " (" + imgName + ")" : "")
            + ": " + messageOf(ex);
    }

    /**
     * Algunas excepciones de E/S solo traen la ruta como mensaje
     * (e.g. FileAlreadyExistsException), así que se indica también el tipo.
     */
    private String messageOf(Exception ex) {
        return ex.getClass().getSimpleName()
            + (ex.getMessage() != null ? " - " + ex.getMessage() : "");
    }
}
