package com.wordtomarkdown;

import com.vladsch.flexmark.html2md.converter.FlexmarkHtmlConverter;
import com.vladsch.flexmark.util.data.DataHolder;
import com.vladsch.flexmark.util.data.MutableDataSet;
import org.zwobble.mammoth.DocumentConverter;
import org.zwobble.mammoth.Result;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Conversión de documentos Word a Markdown. No depende de la interfaz gráfica,
 * de modo que puede usarse y probarse por separado.
 *
 * <p>El flujo es {@code .docx → [Mammoth] → HTML → [flexmark] → .md}, ya que la
 * librería Java de Mammoth no ofrece conversión directa a Markdown.
 */
public class ConversionService implements Converter {

    private static final String DOCX_EXTENSION = ".docx";

    /** Sufijo de la carpeta donde se extraen las imágenes de un documento. */
    private static final String IMAGE_DIR_SUFFIX = "_images";

    /** Fragmentos de alt text con los que Word marca las descripciones generadas por IA. */
    private static final List<String> AI_ALT_TEXT_MARKERS = List.of(
        "ia puede ser",
        "generated by ai",
        "generado por ia"
    );

    /** Bytes que se leen del principio del archivo para reconocer su formato real. */
    private static final int FORMAT_SAMPLE_BYTES = 1024;

    /** Niveles del índice de Word que se traducen a lista anidada. */
    private static final int INDEX_LEVELS = 6;

    /**
     * Estilos que Mammoth no reconoce por sí solo. El nombre que guarda el .docx
     * suele ser el inglés aunque Word esté en español, pero algunos documentos
     * traen el traducido, así que se contemplan los dos.
     */
    private static final List<String> STYLE_MAP = styleMap();

    /**
     * Encabezados con almohadilla ({@code # Título}) en lugar de subrayados, que
     * son los que entienden todos los visores.
     */
    private static final DataHolder MARKDOWN_OPTIONS = new MutableDataSet()
        .set(FlexmarkHtmlConverter.SETEXT_HEADINGS, false)
        .toImmutable();

    private final MarkdownCleaner cleaner = new MarkdownCleaner();
    private final WordNumbering numbering = new WordNumbering();

    @Override
    public ConversionDirection direction() {
        return ConversionDirection.WORD_TO_MARKDOWN;
    }

    @Override
    public boolean isInput(File file) {
        return isDocx(file);
    }

    @Override
    public List<File> findInputFiles(File folder) {
        return findDocxFiles(folder);
    }

    /** true si el archivo es un documento Word convertible. */
    public boolean isDocx(File file) {
        return file != null
            && file.isFile()
            && hasDocxExtension(file.getName())
            && !isWordTempFile(file.getName());
    }

    /**
     * Documentos .docx directamente contenidos en la carpeta, ordenados por nombre.
     * No se recorren las subcarpetas.
     *
     * <p>Se ignoran los archivos temporales que Word deja al abrir un documento
     * ("~$nombre.docx"), que no son documentos válidos.
     */
    public List<File> findDocxFiles(File folder) {
        if (folder == null || !folder.isDirectory()) {
            return List.of();
        }
        File[] files = folder.listFiles(f -> f.isFile()
            && hasDocxExtension(f.getName())
            && !isWordTempFile(f.getName()));
        if (files == null) {
            return List.of();
        }
        return Arrays.stream(files)
            .sorted(Comparator.comparing(File::getName, String.CASE_INSENSITIVE_ORDER))
            .toList();
    }

    /** Nombre del documento sin la extensión .docx. */
    public String baseNameOf(File docx) {
        String name = docx.getName();
        return hasDocxExtension(name) ? name.substring(0, name.length() - DOCX_EXTENSION.length()) : name;
    }

    /**
     * Convierte un documento y escribe el .md junto al original. Nunca lanza:
     * los fallos se describen en el {@link ConversionResult} devuelto.
     */
    @Override
    public ConversionResult convert(File docx) {
        String baseName = baseNameOf(docx);
        File parent = docx.getAbsoluteFile().getParentFile();
        File output = new File(parent, baseName + ".md");
        Path imageDir = parent.toPath().resolve(baseName + IMAGE_DIR_SUFFIX);

        // Numera las imágenes encontradas (para nombres únicos) y contabiliza
        // por separado las extraídas con éxito y las que fallaron.
        AtomicInteger imageCounter = new AtomicInteger(0);
        AtomicInteger imagesOk = new AtomicInteger(0);
        List<String> imageErrors = Collections.synchronizedList(new ArrayList<>());

        try {
            DocumentConverter converter = withStyleMap(new DocumentConverter())
                .imageConverter(image -> {
                    Map<String, String> attrs = new HashMap<>();
                    int index = imageCounter.incrementAndGet();
                    String imgName = null;
                    try {
                        Files.createDirectories(imageDir);
                        imgName = "image" + index + "." + extensionFor(image.getContentType());
                        try (InputStream is = image.getInputStream()) {
                            Files.copy(is, imageDir.resolve(imgName));
                        }
                        attrs.put("src", baseName + IMAGE_DIR_SUFFIX + "/" + imgName);
                        attrs.put("alt", cleanAltText(image.getAltText().orElse(null), index));
                        imagesOk.incrementAndGet();
                    } catch (Exception ex) {
                        // Una imagen ilegible no debe abortar el documento, pero tampoco
                        // puede pasar inadvertida: queda anotada y señalada en el Markdown.
                        imageErrors.add(describeImageError(index, imgName, ex));
                        attrs.put("src", "");
                        attrs.put("alt", "imagen " + index + " (no se pudo extraer)");
                    }
                    return attrs;
                });

            Result<String> htmlResult = converter.convertToHtml(docx);
            Set<String> warnings = htmlResult.getWarnings();

            String markdown = FlexmarkHtmlConverter.builder(MARKDOWN_OPTIONS)
                .build()
                .convert(htmlResult.getValue());

            // La numeración automática de los encabezados ("3.1") no está en el
            // texto: hay que leerla del propio .docx y devolvérsela al Markdown.
            String clean = cleaner.clean(markdown, numbering.readFrom(docx));
            Files.writeString(output.toPath(), clean, StandardCharsets.UTF_8);

            return new ConversionResult(
                direction(), docx, output, true, null,
                List.copyOf(warnings),
                imagesOk.get(),
                List.copyOf(imageErrors),
                imageDir
            );

        } catch (Exception ex) {
            return ConversionResult.failure(direction(), docx, output, imageDir, describeFailure(docx, ex));
        }
    }

    /**
     * Explica por qué falló el documento. Antes de dar el error técnico se mira
     * qué es el archivo en realidad: lo más habitual es que no sea un .docx sino
     * otra cosa con esa extensión (una página web guardada, un PDF, un .doc
     * antiguo), y ahí el mensaje de la librería no ayuda nada.
     */
    private String describeFailure(File docx, Exception ex) {
        String realFormat = detectFormat(docx);
        if (realFormat == null) {
            return messageOf(ex);
        }
        return "No es un documento Word (.docx) válido: " + realFormat
            + ". Ábrelo en Word y usa Guardar como > Documento de Word (.docx).";
    }

    /**
     * Describe el formato real del archivo si no es un .docx, o null si sí lo
     * parece (empieza por la firma de un ZIP) y el fallo viene de otra causa.
     */
    private String detectFormat(File file) {
        byte[] head = firstBytes(file, FORMAT_SAMPLE_BYTES);
        if (head.length == 0) {
            return "el archivo está vacío o no se puede leer";
        }
        if (startsWith(head, 'P', 'K')) {
            return null; // es un ZIP: el problema es otro
        }
        if (startsWith(head, (char) 0xD0, (char) 0xCF, (char) 0x11, (char) 0xE0)) {
            return "es un documento de Word anterior a 2007 (.doc)";
        }
        if (startsWith(head, '%', 'P', 'D', 'F')) {
            return "es un PDF con la extensión cambiada";
        }
        if (startsWith(head, '{', '\\', 'r', 't', 'f')) {
            return "es un archivo RTF con la extensión cambiada";
        }
        String text = new String(head, StandardCharsets.ISO_8859_1).toLowerCase();
        if (text.contains("<!doctype html") || text.contains("<html")) {
            return "es una página web (HTML) guardada con la extensión .docx";
        }
        return "el contenido no tiene el formato de un documento Word";
    }

    private byte[] firstBytes(File file, int count) {
        try (InputStream is = new FileInputStream(file)) {
            return is.readNBytes(count);
        } catch (IOException ex) {
            return new byte[0];
        }
    }

    private boolean startsWith(byte[] content, char... signature) {
        if (content.length < signature.length) {
            return false;
        }
        for (int i = 0; i < signature.length; i++) {
            if ((content[i] & 0xFF) != signature[i]) {
                return false;
            }
        }
        return true;
    }

    private DocumentConverter withStyleMap(DocumentConverter converter) {
        DocumentConverter mapped = converter;
        for (String rule : STYLE_MAP) {
            mapped = mapped.addStyleMap(rule);
        }
        return mapped;
    }

    /**
     * Reglas de estilo → HTML para lo que Mammoth deja como párrafo suelto: el
     * título del documento y las entradas del índice, que se convierten en una
     * lista anidada para conservar la jerarquía (3 → 3.1 → 3.1.1 ...).
     */
    private static List<String> styleMap() {
        List<String> rules = new ArrayList<>(List.of(
            "p[style-name='Title'] => h1:fresh",
            "p[style-name='Título'] => h1:fresh",
            "p[style-name='Subtitle'] => h2:fresh",
            "p[style-name='Subtítulo'] => h2:fresh",
            "p[style-name='TOC Heading'] => h1:fresh",
            "p[style-name='Tabla de contenido'] => h1:fresh",
            // Estilos propios de la conversión inversa ({@link WordStyles}): sin
            // estas reglas, un .docx generado por el programa vuelve a Markdown
            // perdiendo las citas, los bloques de código y el código en línea.
            "p[style-name='Quote'] => blockquote:fresh",
            // Cada línea del bloque es un párrafo: se unen en un solo <pre>.
            "p[style-name='Code Block'] => pre:separator('\\n')",
            "r[style-name='Code Char'] => code"
        ));
        for (int level = 1; level <= INDEX_LEVELS; level++) {
            // Cada nivel cuelga del anterior: "ul > li > ul > li:fresh"
            String nesting = "ul > li > ".repeat(level - 1) + "ul > li:fresh";
            rules.add("p[style-name='toc " + level + "'] => " + nesting);
            rules.add("p[style-name='TDC " + level + "'] => " + nesting);
            // Encabezados con el nombre de estilo en español
            rules.add("p[style-name='Título " + level + "'] => h" + Math.min(level, 6) + ":fresh");
        }
        return List.copyOf(rules);
    }

    private boolean hasDocxExtension(String name) {
        return name.toLowerCase().endsWith(DOCX_EXTENSION);
    }

    /** Archivos "~$nombre.docx" (temporales de Word) y ocultos. */
    private boolean isWordTempFile(String name) {
        return name.startsWith("~$") || name.startsWith(".");
    }

    /** Extensión a partir del tipo MIME, normalizando compuestos como "svg+xml". */
    private String extensionFor(String contentType) {
        if (contentType == null || !contentType.contains("/")) {
            return "png";
        }
        String ext = contentType.split("/")[1];
        return ext.contains("+") ? ext.split("\\+")[0] : ext;
    }

    /**
     * Alt text utilizable: descarta el vacío y los avisos que añade automáticamente
     * la IA de Word, sustituyéndolos por un texto genérico.
     */
    private String cleanAltText(String altText, int index) {
        if (altText != null) {
            String trimmed = altText.trim();
            String lower = trimmed.toLowerCase();
            boolean generatedByAi = AI_ALT_TEXT_MARKERS.stream().anyMatch(lower::contains);
            if (!trimmed.isBlank() && !generatedByAi) {
                return trimmed;
            }
        }
        return "imagen " + index;
    }

    private String describeImageError(int index, String imgName, Exception ex) {
        return "imagen " + index
            + (imgName != null ? " (" + imgName + ")" : "")
            + ": " + messageOf(ex);
    }

    /**
     * Algunas excepciones de E/S solo traen la ruta como mensaje
     * (e.g. FileAlreadyExistsException), así que se indica también el tipo.
     */
    private String messageOf(Exception ex) {
        return ex.getClass().getSimpleName()
            + (ex.getMessage() != null ? " - " + ex.getMessage() : "");
    }
}
